title: Átila Braga _ Developer
description: >
  **Átila Braga** Android developer
  trying to make difference within
  your community [GDG](http://emjuizdefora.com/gdgjf).
copyright: Untitled
sass:
  sass_dir: assets/sass
url: http://localhost:4000
disqus_shortname: stratajekylldemo
facebook_username: atila.braga.5
twitter_username: "@atilabraga"
#linkedin_username: "#"
#instagram_username:
#pinterest_username:
#flickr_username:
github_username:  "atilabraga"
feed_icon: rss
email: "braga.atila@gmail.com"
gems: [jekyll-paginate]
paginate_path: "/page/:num/"
paginate: 5
